// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/proto/v1/screen/screen.proto

package screen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScreenStatus int32

const (
	ScreenStatus_SCREEN_STATUS_UNSPECIFIED ScreenStatus = 0
	ScreenStatus_SCREEN_STATUS_OFFLINE     ScreenStatus = 1
	ScreenStatus_SCREEN_STATUS_ONLINE      ScreenStatus = 2
	ScreenStatus_SCREEN_STATUS_MAINTENANCE ScreenStatus = 3
)

// Enum value maps for ScreenStatus.
var (
	ScreenStatus_name = map[int32]string{
		0: "SCREEN_STATUS_UNSPECIFIED",
		1: "SCREEN_STATUS_OFFLINE",
		2: "SCREEN_STATUS_ONLINE",
		3: "SCREEN_STATUS_MAINTENANCE",
	}
	ScreenStatus_value = map[string]int32{
		"SCREEN_STATUS_UNSPECIFIED": 0,
		"SCREEN_STATUS_OFFLINE":     1,
		"SCREEN_STATUS_ONLINE":      2,
		"SCREEN_STATUS_MAINTENANCE": 3,
	}
)

func (x ScreenStatus) Enum() *ScreenStatus {
	p := new(ScreenStatus)
	*p = x
	return p
}

func (x ScreenStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScreenStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_screen_screen_proto_enumTypes[0].Descriptor()
}

func (ScreenStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_screen_screen_proto_enumTypes[0]
}

func (x ScreenStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScreenStatus.Descriptor instead.
func (ScreenStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_screen_screen_proto_rawDescGZIP(), []int{0}
}

type Screen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Status        ScreenStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=screen.v1.ScreenStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Screen) Reset() {
	*x = Screen{}
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Screen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screen) ProtoMessage() {}

func (x *Screen) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screen.ProtoReflect.Descriptor instead.
func (*Screen) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_screen_screen_proto_rawDescGZIP(), []int{0}
}

func (x *Screen) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Screen) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Screen) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Screen) GetStatus() ScreenStatus {
	if x != nil {
		return x.Status
	}
	return ScreenStatus_SCREEN_STATUS_UNSPECIFIED
}

func (x *Screen) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Screen) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScreenRequest) Reset() {
	*x = CreateScreenRequest{}
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScreenRequest) ProtoMessage() {}

func (x *CreateScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScreenRequest.ProtoReflect.Descriptor instead.
func (*CreateScreenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_screen_screen_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScreenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScreenRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type CreateScreenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Screen        *Screen                `protobuf:"bytes,1,opt,name=screen,proto3" json:"screen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScreenResponse) Reset() {
	*x = CreateScreenResponse{}
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScreenResponse) ProtoMessage() {}

func (x *CreateScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScreenResponse.ProtoReflect.Descriptor instead.
func (*CreateScreenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_screen_screen_proto_rawDescGZIP(), []int{2}
}

func (x *CreateScreenResponse) GetScreen() *Screen {
	if x != nil {
		return x.Screen
	}
	return nil
}

type GetScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScreenRequest) Reset() {
	*x = GetScreenRequest{}
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreenRequest) ProtoMessage() {}

func (x *GetScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreenRequest.ProtoReflect.Descriptor instead.
func (*GetScreenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_screen_screen_proto_rawDescGZIP(), []int{3}
}

func (x *GetScreenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetScreenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Screen        *Screen                `protobuf:"bytes,1,opt,name=screen,proto3" json:"screen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScreenResponse) Reset() {
	*x = GetScreenResponse{}
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreenResponse) ProtoMessage() {}

func (x *GetScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreenResponse.ProtoReflect.Descriptor instead.
func (*GetScreenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_screen_screen_proto_rawDescGZIP(), []int{4}
}

func (x *GetScreenResponse) GetScreen() *Screen {
	if x != nil {
		return x.Screen
	}
	return nil
}

type UpdateScreenStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        ScreenStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=screen.v1.ScreenStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScreenStatusRequest) Reset() {
	*x = UpdateScreenStatusRequest{}
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScreenStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScreenStatusRequest) ProtoMessage() {}

func (x *UpdateScreenStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScreenStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateScreenStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_screen_screen_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateScreenStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateScreenStatusRequest) GetStatus() ScreenStatus {
	if x != nil {
		return x.Status
	}
	return ScreenStatus_SCREEN_STATUS_UNSPECIFIED
}

type UpdateScreenStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Screen        *Screen                `protobuf:"bytes,1,opt,name=screen,proto3" json:"screen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScreenStatusResponse) Reset() {
	*x = UpdateScreenStatusResponse{}
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScreenStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScreenStatusResponse) ProtoMessage() {}

func (x *UpdateScreenStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_screen_screen_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScreenStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateScreenStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_screen_screen_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateScreenStatusResponse) GetScreen() *Screen {
	if x != nil {
		return x.Screen
	}
	return nil
}

var File_api_proto_v1_screen_screen_proto protoreflect.FileDescriptor

const file_api_proto_v1_screen_screen_proto_rawDesc = "" +
	"\n" +
	" api/proto/v1/screen/screen.proto\x12\tscreen.v1\"\xb7\x01\n" +
	"\x06Screen\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.screen.v1.ScreenStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"E\n" +
	"\x13CreateScreenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"A\n" +
	"\x14CreateScreenResponse\x12)\n" +
	"\x06screen\x18\x01 \x01(\v2\x11.screen.v1.ScreenR\x06screen\"\"\n" +
	"\x10GetScreenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x11GetScreenResponse\x12)\n" +
	"\x06screen\x18\x01 \x01(\v2\x11.screen.v1.ScreenR\x06screen\"\\\n" +
	"\x19UpdateScreenStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.screen.v1.ScreenStatusR\x06status\"G\n" +
	"\x1aUpdateScreenStatusResponse\x12)\n" +
	"\x06screen\x18\x01 \x01(\v2\x11.screen.v1.ScreenR\x06screen*\x81\x01\n" +
	"\fScreenStatus\x12\x1d\n" +
	"\x19SCREEN_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SCREEN_STATUS_OFFLINE\x10\x01\x12\x18\n" +
	"\x14SCREEN_STATUS_ONLINE\x10\x02\x12\x1d\n" +
	"\x19SCREEN_STATUS_MAINTENANCE\x10\x032\x8b\x02\n" +
	"\rScreenService\x12O\n" +
	"\fCreateScreen\x12\x1e.screen.v1.CreateScreenRequest\x1a\x1f.screen.v1.CreateScreenResponse\x12F\n" +
	"\tGetScreen\x12\x1b.screen.v1.GetScreenRequest\x1a\x1c.screen.v1.GetScreenResponse\x12a\n" +
	"\x12UpdateScreenStatus\x12$.screen.v1.UpdateScreenStatusRequest\x1a%.screen.v1.UpdateScreenStatusResponseBGZEgithub.com/zaeemnadeem/golang-example-repo/api/proto/v1/screen;screenb\x06proto3"

var (
	file_api_proto_v1_screen_screen_proto_rawDescOnce sync.Once
	file_api_proto_v1_screen_screen_proto_rawDescData []byte
)

func file_api_proto_v1_screen_screen_proto_rawDescGZIP() []byte {
	file_api_proto_v1_screen_screen_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_screen_screen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_screen_screen_proto_rawDesc), len(file_api_proto_v1_screen_screen_proto_rawDesc)))
	})
	return file_api_proto_v1_screen_screen_proto_rawDescData
}

var file_api_proto_v1_screen_screen_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_screen_screen_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_v1_screen_screen_proto_goTypes = []any{
	(ScreenStatus)(0),                  // 0: screen.v1.ScreenStatus
	(*Screen)(nil),                     // 1: screen.v1.Screen
	(*CreateScreenRequest)(nil),        // 2: screen.v1.CreateScreenRequest
	(*CreateScreenResponse)(nil),       // 3: screen.v1.CreateScreenResponse
	(*GetScreenRequest)(nil),           // 4: screen.v1.GetScreenRequest
	(*GetScreenResponse)(nil),          // 5: screen.v1.GetScreenResponse
	(*UpdateScreenStatusRequest)(nil),  // 6: screen.v1.UpdateScreenStatusRequest
	(*UpdateScreenStatusResponse)(nil), // 7: screen.v1.UpdateScreenStatusResponse
}
var file_api_proto_v1_screen_screen_proto_depIdxs = []int32{
	0, // 0: screen.v1.Screen.status:type_name -> screen.v1.ScreenStatus
	1, // 1: screen.v1.CreateScreenResponse.screen:type_name -> screen.v1.Screen
	1, // 2: screen.v1.GetScreenResponse.screen:type_name -> screen.v1.Screen
	0, // 3: screen.v1.UpdateScreenStatusRequest.status:type_name -> screen.v1.ScreenStatus
	1, // 4: screen.v1.UpdateScreenStatusResponse.screen:type_name -> screen.v1.Screen
	2, // 5: screen.v1.ScreenService.CreateScreen:input_type -> screen.v1.CreateScreenRequest
	4, // 6: screen.v1.ScreenService.GetScreen:input_type -> screen.v1.GetScreenRequest
	6, // 7: screen.v1.ScreenService.UpdateScreenStatus:input_type -> screen.v1.UpdateScreenStatusRequest
	3, // 8: screen.v1.ScreenService.CreateScreen:output_type -> screen.v1.CreateScreenResponse
	5, // 9: screen.v1.ScreenService.GetScreen:output_type -> screen.v1.GetScreenResponse
	7, // 10: screen.v1.ScreenService.UpdateScreenStatus:output_type -> screen.v1.UpdateScreenStatusResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_v1_screen_screen_proto_init() }
func file_api_proto_v1_screen_screen_proto_init() {
	if File_api_proto_v1_screen_screen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_screen_screen_proto_rawDesc), len(file_api_proto_v1_screen_screen_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_screen_screen_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_screen_screen_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_screen_screen_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_screen_screen_proto_msgTypes,
	}.Build()
	File_api_proto_v1_screen_screen_proto = out.File
	file_api_proto_v1_screen_screen_proto_goTypes = nil
	file_api_proto_v1_screen_screen_proto_depIdxs = nil
}
