// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: api/proto/v1/screen/screen.proto

package screen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScreenService_CreateScreen_FullMethodName       = "/screen.v1.ScreenService/CreateScreen"
	ScreenService_GetScreen_FullMethodName          = "/screen.v1.ScreenService/GetScreen"
	ScreenService_UpdateScreenStatus_FullMethodName = "/screen.v1.ScreenService/UpdateScreenStatus"
)

// ScreenServiceClient is the client API for ScreenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScreenService manages the lifecycle and metadata of signage screens
type ScreenServiceClient interface {
	CreateScreen(ctx context.Context, in *CreateScreenRequest, opts ...grpc.CallOption) (*CreateScreenResponse, error)
	GetScreen(ctx context.Context, in *GetScreenRequest, opts ...grpc.CallOption) (*GetScreenResponse, error)
	UpdateScreenStatus(ctx context.Context, in *UpdateScreenStatusRequest, opts ...grpc.CallOption) (*UpdateScreenStatusResponse, error)
}

type screenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScreenServiceClient(cc grpc.ClientConnInterface) ScreenServiceClient {
	return &screenServiceClient{cc}
}

func (c *screenServiceClient) CreateScreen(ctx context.Context, in *CreateScreenRequest, opts ...grpc.CallOption) (*CreateScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateScreenResponse)
	err := c.cc.Invoke(ctx, ScreenService_CreateScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *screenServiceClient) GetScreen(ctx context.Context, in *GetScreenRequest, opts ...grpc.CallOption) (*GetScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScreenResponse)
	err := c.cc.Invoke(ctx, ScreenService_GetScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *screenServiceClient) UpdateScreenStatus(ctx context.Context, in *UpdateScreenStatusRequest, opts ...grpc.CallOption) (*UpdateScreenStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateScreenStatusResponse)
	err := c.cc.Invoke(ctx, ScreenService_UpdateScreenStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScreenServiceServer is the server API for ScreenService service.
// All implementations must embed UnimplementedScreenServiceServer
// for forward compatibility.
//
// ScreenService manages the lifecycle and metadata of signage screens
type ScreenServiceServer interface {
	CreateScreen(context.Context, *CreateScreenRequest) (*CreateScreenResponse, error)
	GetScreen(context.Context, *GetScreenRequest) (*GetScreenResponse, error)
	UpdateScreenStatus(context.Context, *UpdateScreenStatusRequest) (*UpdateScreenStatusResponse, error)
	mustEmbedUnimplementedScreenServiceServer()
}

// UnimplementedScreenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScreenServiceServer struct{}

func (UnimplementedScreenServiceServer) CreateScreen(context.Context, *CreateScreenRequest) (*CreateScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScreen not implemented")
}
func (UnimplementedScreenServiceServer) GetScreen(context.Context, *GetScreenRequest) (*GetScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScreen not implemented")
}
func (UnimplementedScreenServiceServer) UpdateScreenStatus(context.Context, *UpdateScreenStatusRequest) (*UpdateScreenStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateScreenStatus not implemented")
}
func (UnimplementedScreenServiceServer) mustEmbedUnimplementedScreenServiceServer() {}
func (UnimplementedScreenServiceServer) testEmbeddedByValue()                       {}

// UnsafeScreenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScreenServiceServer will
// result in compilation errors.
type UnsafeScreenServiceServer interface {
	mustEmbedUnimplementedScreenServiceServer()
}

func RegisterScreenServiceServer(s grpc.ServiceRegistrar, srv ScreenServiceServer) {
	// If the following call panics, it indicates UnimplementedScreenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScreenService_ServiceDesc, srv)
}

func _ScreenService_CreateScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScreenServiceServer).CreateScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScreenService_CreateScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScreenServiceServer).CreateScreen(ctx, req.(*CreateScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScreenService_GetScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScreenServiceServer).GetScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScreenService_GetScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScreenServiceServer).GetScreen(ctx, req.(*GetScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScreenService_UpdateScreenStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScreenStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScreenServiceServer).UpdateScreenStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScreenService_UpdateScreenStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScreenServiceServer).UpdateScreenStatus(ctx, req.(*UpdateScreenStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScreenService_ServiceDesc is the grpc.ServiceDesc for ScreenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScreenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "screen.v1.ScreenService",
	HandlerType: (*ScreenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateScreen",
			Handler:    _ScreenService_CreateScreen_Handler,
		},
		{
			MethodName: "GetScreen",
			Handler:    _ScreenService_GetScreen_Handler,
		},
		{
			MethodName: "UpdateScreenStatus",
			Handler:    _ScreenService_UpdateScreenStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/screen/screen.proto",
}
