// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/proto/v1/content/content.proto

package content

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentType int32

const (
	ContentType_CONTENT_TYPE_UNSPECIFIED ContentType = 0
	ContentType_CONTENT_TYPE_IMAGE       ContentType = 1
	ContentType_CONTENT_TYPE_VIDEO       ContentType = 2
	ContentType_CONTENT_TYPE_HTML        ContentType = 3
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSPECIFIED",
		1: "CONTENT_TYPE_IMAGE",
		2: "CONTENT_TYPE_VIDEO",
		3: "CONTENT_TYPE_HTML",
	}
	ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSPECIFIED": 0,
		"CONTENT_TYPE_IMAGE":       1,
		"CONTENT_TYPE_VIDEO":       2,
		"CONTENT_TYPE_HTML":        3,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_content_content_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_content_content_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_content_content_proto_rawDescGZIP(), []int{0}
}

type Content struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url             string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Type            ContentType            `protobuf:"varint,4,opt,name=type,proto3,enum=content.v1.ContentType" json:"type,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_api_proto_v1_content_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_content_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_content_content_proto_rawDescGZIP(), []int{0}
}

func (x *Content) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Content) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Content) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Content) GetType() ContentType {
	if x != nil {
		return x.Type
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *Content) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Content) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateContentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url             string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Type            ContentType            `protobuf:"varint,3,opt,name=type,proto3,enum=content.v1.ContentType" json:"type,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateContentRequest) Reset() {
	*x = CreateContentRequest{}
	mi := &file_api_proto_v1_content_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentRequest) ProtoMessage() {}

func (x *CreateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_content_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentRequest.ProtoReflect.Descriptor instead.
func (*CreateContentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_content_content_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateContentRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateContentRequest) GetType() ContentType {
	if x != nil {
		return x.Type
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *CreateContentRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type CreateContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentResponse) Reset() {
	*x = CreateContentResponse{}
	mi := &file_api_proto_v1_content_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentResponse) ProtoMessage() {}

func (x *CreateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_content_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentResponse.ProtoReflect.Descriptor instead.
func (*CreateContentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_content_content_proto_rawDescGZIP(), []int{2}
}

func (x *CreateContentResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type AssignContentToScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ScreenId      string                 `protobuf:"bytes,2,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignContentToScreenRequest) Reset() {
	*x = AssignContentToScreenRequest{}
	mi := &file_api_proto_v1_content_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignContentToScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignContentToScreenRequest) ProtoMessage() {}

func (x *AssignContentToScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_content_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignContentToScreenRequest.ProtoReflect.Descriptor instead.
func (*AssignContentToScreenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_content_content_proto_rawDescGZIP(), []int{3}
}

func (x *AssignContentToScreenRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *AssignContentToScreenRequest) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

type AssignContentToScreenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignContentToScreenResponse) Reset() {
	*x = AssignContentToScreenResponse{}
	mi := &file_api_proto_v1_content_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignContentToScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignContentToScreenResponse) ProtoMessage() {}

func (x *AssignContentToScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_content_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignContentToScreenResponse.ProtoReflect.Descriptor instead.
func (*AssignContentToScreenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_content_content_proto_rawDescGZIP(), []int{4}
}

func (x *AssignContentToScreenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetScreenContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenId      string                 `protobuf:"bytes,1,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScreenContentRequest) Reset() {
	*x = GetScreenContentRequest{}
	mi := &file_api_proto_v1_content_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScreenContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreenContentRequest) ProtoMessage() {}

func (x *GetScreenContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_content_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreenContentRequest.ProtoReflect.Descriptor instead.
func (*GetScreenContentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_content_content_proto_rawDescGZIP(), []int{5}
}

func (x *GetScreenContentRequest) GetScreenId() string {
	if x != nil {
		return x.ScreenId
	}
	return ""
}

type GetScreenContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*Content             `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScreenContentResponse) Reset() {
	*x = GetScreenContentResponse{}
	mi := &file_api_proto_v1_content_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScreenContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreenContentResponse) ProtoMessage() {}

func (x *GetScreenContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_content_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreenContentResponse.ProtoReflect.Descriptor instead.
func (*GetScreenContentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_content_content_proto_rawDescGZIP(), []int{6}
}

func (x *GetScreenContentResponse) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

var File_api_proto_v1_content_content_proto protoreflect.FileDescriptor

const file_api_proto_v1_content_content_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/v1/content/content.proto\x12\n" +
	"content.v1\"\xb8\x01\n" +
	"\aContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12+\n" +
	"\x04type\x18\x04 \x01(\x0e2\x17.content.v1.ContentTypeR\x04type\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\x96\x01\n" +
	"\x14CreateContentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.content.v1.ContentTypeR\x04type\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x05R\x0fdurationSeconds\"F\n" +
	"\x15CreateContentResponse\x12-\n" +
	"\acontent\x18\x01 \x01(\v2\x13.content.v1.ContentR\acontent\"Z\n" +
	"\x1cAssignContentToScreenRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x1b\n" +
	"\tscreen_id\x18\x02 \x01(\tR\bscreenId\"9\n" +
	"\x1dAssignContentToScreenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"6\n" +
	"\x17GetScreenContentRequest\x12\x1b\n" +
	"\tscreen_id\x18\x01 \x01(\tR\bscreenId\"K\n" +
	"\x18GetScreenContentResponse\x12/\n" +
	"\bcontents\x18\x01 \x03(\v2\x13.content.v1.ContentR\bcontents*r\n" +
	"\vContentType\x12\x1c\n" +
	"\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONTENT_TYPE_IMAGE\x10\x01\x12\x16\n" +
	"\x12CONTENT_TYPE_VIDEO\x10\x02\x12\x15\n" +
	"\x11CONTENT_TYPE_HTML\x10\x032\xb3\x02\n" +
	"\x0eContentService\x12T\n" +
	"\rCreateContent\x12 .content.v1.CreateContentRequest\x1a!.content.v1.CreateContentResponse\x12l\n" +
	"\x15AssignContentToScreen\x12(.content.v1.AssignContentToScreenRequest\x1a).content.v1.AssignContentToScreenResponse\x12]\n" +
	"\x10GetScreenContent\x12#.content.v1.GetScreenContentRequest\x1a$.content.v1.GetScreenContentResponseBIZGgithub.com/zaeemnadeem/golang-example-repo/api/proto/v1/content;contentb\x06proto3"

var (
	file_api_proto_v1_content_content_proto_rawDescOnce sync.Once
	file_api_proto_v1_content_content_proto_rawDescData []byte
)

func file_api_proto_v1_content_content_proto_rawDescGZIP() []byte {
	file_api_proto_v1_content_content_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_content_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_content_content_proto_rawDesc), len(file_api_proto_v1_content_content_proto_rawDesc)))
	})
	return file_api_proto_v1_content_content_proto_rawDescData
}

var file_api_proto_v1_content_content_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_content_content_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_v1_content_content_proto_goTypes = []any{
	(ContentType)(0),                      // 0: content.v1.ContentType
	(*Content)(nil),                       // 1: content.v1.Content
	(*CreateContentRequest)(nil),          // 2: content.v1.CreateContentRequest
	(*CreateContentResponse)(nil),         // 3: content.v1.CreateContentResponse
	(*AssignContentToScreenRequest)(nil),  // 4: content.v1.AssignContentToScreenRequest
	(*AssignContentToScreenResponse)(nil), // 5: content.v1.AssignContentToScreenResponse
	(*GetScreenContentRequest)(nil),       // 6: content.v1.GetScreenContentRequest
	(*GetScreenContentResponse)(nil),      // 7: content.v1.GetScreenContentResponse
}
var file_api_proto_v1_content_content_proto_depIdxs = []int32{
	0, // 0: content.v1.Content.type:type_name -> content.v1.ContentType
	0, // 1: content.v1.CreateContentRequest.type:type_name -> content.v1.ContentType
	1, // 2: content.v1.CreateContentResponse.content:type_name -> content.v1.Content
	1, // 3: content.v1.GetScreenContentResponse.contents:type_name -> content.v1.Content
	2, // 4: content.v1.ContentService.CreateContent:input_type -> content.v1.CreateContentRequest
	4, // 5: content.v1.ContentService.AssignContentToScreen:input_type -> content.v1.AssignContentToScreenRequest
	6, // 6: content.v1.ContentService.GetScreenContent:input_type -> content.v1.GetScreenContentRequest
	3, // 7: content.v1.ContentService.CreateContent:output_type -> content.v1.CreateContentResponse
	5, // 8: content.v1.ContentService.AssignContentToScreen:output_type -> content.v1.AssignContentToScreenResponse
	7, // 9: content.v1.ContentService.GetScreenContent:output_type -> content.v1.GetScreenContentResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_v1_content_content_proto_init() }
func file_api_proto_v1_content_content_proto_init() {
	if File_api_proto_v1_content_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_content_content_proto_rawDesc), len(file_api_proto_v1_content_content_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_content_content_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_content_content_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_content_content_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_content_content_proto_msgTypes,
	}.Build()
	File_api_proto_v1_content_content_proto = out.File
	file_api_proto_v1_content_content_proto_goTypes = nil
	file_api_proto_v1_content_content_proto_depIdxs = nil
}
